#!/bin/bash

source /etc/power-web-service.conf

ledindicator $WEB_SERVICE_INDICATOR_LED ON

java -jar -DPOWER_DEVICE_PIN=$POWER_DEVICE_PIN /usr/local/sbin/powerwsd.jar

ledindicator $WEB_SERVICE_INDICATOR_LED OFF